### ISSUE TITLE
Input Mapping/Remapping

### ISSUE THREAD

**Issue by odecay** [fishfolks/punchy#28]
Support for mapping of inputs to keyboard/controller buttons via a menu/saved + loaded from a settings asset.

- [x] Setup the data ( i.e. structs/enums ) necessary for the input map. The idea is to map raw control events such as keyboard and gamepad to something like a `GameInput` event in terms of the actual actions that can be taken in game. #52
- [x] Create a thin storage abstraction that works for web and desktop #79 
- [x] #87

**Comment by odecay** [comment]
I don't know much about browser local storage but I was thinking it might need special attention, glad to hear you already have thoughts about it. Thin storage layer sounds useful and progress saving also sounds like something we should have.

**Comment by zicklag** [comment]
I think this is the next thing I should work on after #11 get's finished up with #50, can you assign it to me?

My plan so far is:

- [ ] Setup the data ( i.e. structs/enums ) necessary for the input map. The idea is to map raw control events such as keyboard and gamepad to something like a `GameInput` event in terms of the actual actions that can be taken in game.
- [ ] Load default input mappings from an asset

Once we get that, the next steps would be:

- [ ] Create a thin storage abstraction that works for web and desktop
- [ ] Create a menu for editing the input mappings that saves the settings using the storage abstraction and also has a button to reset the settings to their defaults.

**Comment by zicklag** [comment]
It looks like this input plugin is pretty well designed, so I'll try that out and see how it goes: https://github.com/Leafwing-Studios/leafwing-input-manager.

**Comment by zicklag** [comment]
@odecay I ran into a Bevy problem detecting DPad inputs, and I opened a PR to fix it, but obviously if that PR is going to be merged it will be into Bevy 0.8.0-dev, so we can't just use it without switching to Bevy from git.

I am going to be working on getting analog sticks working with `leafwing-input-manager`, so that could save us from needing DPad support for now, though.

I did have a question, though, what's our "policy" for crate dependencies right now. Are we fine using dependencies from git if we have to? For instance, if I add support for analog sticks in `leafwing-input` and they aren't ready to do a crates.io release yet, are we good just continuing with a git dependency?

**Comment by odecay** [comment]
I feel like it should be fine to use git dependencies especially if it is blocking us from supporting something, with the goal to move back to release deps when the newer version is released.

**Comment by zicklag** [comment]
Just got a storage abstraction working in the browser, now I just need to implement it for native, which should be easy.

**Comment by zicklag** [comment]
Storage abstraction is ready! #79 

Now I'll work on the settings menu and allowing you to configure input mappings.

**Comment by odecay** [comment]
This is done, anything else on top of what we have should be considered as improvements.
